### ISSUE TITLE
Selenium IDE-SetBlocks Global: How to call function, defined in TC1 from another test case TC2

### ISSUE THREAD

**Issue by spasova** [SeLite/SelBlocksGlobal#1]
Hello,

I tried to define function with function/endFunction (it contains only selenium IDE commands, actually commands to login in my app) in TC1 and to call it from TC2, but when I run the script there is infinite loop.
Actually, I want to define login steps in TC1 and to call this TC in the beginning of the other scripts.
How to do this with function/endFunction and command call?

Thank you!
Regards,
Olya Spasova

**Comment by peter-kehl** [comment]
Hi Olya,

It used to work. There may be a problem. I will investigate. However, it will take about 10 days before I start on this.

**Comment by peter-kehl** [comment]
What is your version of Selenium IDE? I haven't tested SeLite with the newest Selenium IDE.

**Comment by peter-kehl** [comment]
I confirm that SeLite SelBlocksGlobal runs function across test cases with Selenium IDE 2.9.1.

Follow http://selite.github.io/PackagedScripts and http://selite.github.io/InstallFromSource to get selenese-scripts/various folder of SelBlocksGlobal. Open sel-blocks-global_suite.html as a Selenium IDE test suite. Run test case 'plain_function_call_case'.

If that works but your own test suite doesn't work, the problem is probably in your test suite. If you believe otherwise, follow http://selite.github.io/ReportingIssues.

**Comment by spasova** [comment]
Hi,
Thank you:-)
Yes, it works, I managed  to call a function between TCs in same suite
Actually the problem was that I had to install Extension Sequencer and TestCase Debug Context.
Thank you again,
- Olya

**Comment by peter-kehl** [comment]
Hi Olya,

You could get more value out of SeLite and SelBlocks Global. However, they can progress only if you promote these projects.

Please, would you star https://github.com/SeLite/SelBlocksGlobal, https://github.com/SeLite/Selite and https://github.com/SeLite/SeLite.github.io.

Would you vote for http://selite.github.io/ThirdPartyIssues, please.
